package com.anrong.user.po;

public class SysDepartment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_department.id
     *
     * @mbg.generated Thu Feb 08 14:40:17 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_department.code
     *
     * @mbg.generated Thu Feb 08 14:40:17 CST 2018
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_department.name
     *
     * @mbg.generated Thu Feb 08 14:40:17 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_department.enterpriseId
     *
     * @mbg.generated Thu Feb 08 14:40:17 CST 2018
     */
    private Integer enterpriseid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_department.id
     *
     * @return the value of sys_department.id
     *
     * @mbg.generated Thu Feb 08 14:40:17 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_department.id
     *
     * @param id the value for sys_department.id
     *
     * @mbg.generated Thu Feb 08 14:40:17 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_department.code
     *
     * @return the value of sys_department.code
     *
     * @mbg.generated Thu Feb 08 14:40:17 CST 2018
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_department.code
     *
     * @param code the value for sys_department.code
     *
     * @mbg.generated Thu Feb 08 14:40:17 CST 2018
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_department.name
     *
     * @return the value of sys_department.name
     *
     * @mbg.generated Thu Feb 08 14:40:17 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_department.name
     *
     * @param name the value for sys_department.name
     *
     * @mbg.generated Thu Feb 08 14:40:17 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_department.enterpriseId
     *
     * @return the value of sys_department.enterpriseId
     *
     * @mbg.generated Thu Feb 08 14:40:17 CST 2018
     */
    public Integer getEnterpriseid() {
        return enterpriseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_department.enterpriseId
     *
     * @param enterpriseid the value for sys_department.enterpriseId
     *
     * @mbg.generated Thu Feb 08 14:40:17 CST 2018
     */
    public void setEnterpriseid(Integer enterpriseid) {
        this.enterpriseid = enterpriseid;
    }
}