package com.anrong.user.po;

public class SysEnterprise {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_enterprise.id
     *
     * @mbg.generated Thu Feb 08 14:37:01 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_enterprise.name
     *
     * @mbg.generated Thu Feb 08 14:37:01 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_enterprise.deleteFlag
     *
     * @mbg.generated Thu Feb 08 14:37:01 CST 2018
     */
    private Integer deleteflag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_enterprise.code
     *
     * @mbg.generated Thu Feb 08 14:37:01 CST 2018
     */
    private String code;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_enterprise.id
     *
     * @return the value of sys_enterprise.id
     *
     * @mbg.generated Thu Feb 08 14:37:01 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_enterprise.id
     *
     * @param id the value for sys_enterprise.id
     *
     * @mbg.generated Thu Feb 08 14:37:01 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_enterprise.name
     *
     * @return the value of sys_enterprise.name
     *
     * @mbg.generated Thu Feb 08 14:37:01 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_enterprise.name
     *
     * @param name the value for sys_enterprise.name
     *
     * @mbg.generated Thu Feb 08 14:37:01 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_enterprise.deleteFlag
     *
     * @return the value of sys_enterprise.deleteFlag
     *
     * @mbg.generated Thu Feb 08 14:37:01 CST 2018
     */
    public Integer getDeleteflag() {
        return deleteflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_enterprise.deleteFlag
     *
     * @param deleteflag the value for sys_enterprise.deleteFlag
     *
     * @mbg.generated Thu Feb 08 14:37:01 CST 2018
     */
    public void setDeleteflag(Integer deleteflag) {
        this.deleteflag = deleteflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_enterprise.code
     *
     * @return the value of sys_enterprise.code
     *
     * @mbg.generated Thu Feb 08 14:37:01 CST 2018
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_enterprise.code
     *
     * @param code the value for sys_enterprise.code
     *
     * @mbg.generated Thu Feb 08 14:37:01 CST 2018
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }
}