package com.anrong.user.po;

import java.util.Date;

public class SysEmployee {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_employee.id
     *
     * @mbg.generated Thu Feb 08 14:08:51 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_employee.name
     *
     * @mbg.generated Thu Feb 08 14:08:51 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_employee.mobile
     *
     * @mbg.generated Thu Feb 08 14:08:51 CST 2018
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_employee.email
     *
     * @mbg.generated Thu Feb 08 14:08:51 CST 2018
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_employee.createTime
     *
     * @mbg.generated Thu Feb 08 14:08:51 CST 2018
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_employee.updateTime
     *
     * @mbg.generated Thu Feb 08 14:08:51 CST 2018
     */
    private Date updatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_employee.deleteFlag
     *
     * @mbg.generated Thu Feb 08 14:08:51 CST 2018
     */
    private Integer deleteflag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_employee.enterpriseId
     *
     * @mbg.generated Thu Feb 08 14:08:51 CST 2018
     */
    private Integer enterpriseid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_employee.departmentId
     *
     * @mbg.generated Thu Feb 08 14:08:51 CST 2018
     */
    private Integer departmentid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_employee.userId
     *
     * @mbg.generated Thu Feb 08 14:08:51 CST 2018
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_employee.roleId
     *
     * @mbg.generated Thu Feb 08 14:08:51 CST 2018
     */
    private Integer roleid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_employee.id
     *
     * @return the value of sys_employee.id
     *
     * @mbg.generated Thu Feb 08 14:08:51 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_employee.id
     *
     * @param id the value for sys_employee.id
     *
     * @mbg.generated Thu Feb 08 14:08:51 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_employee.name
     *
     * @return the value of sys_employee.name
     *
     * @mbg.generated Thu Feb 08 14:08:51 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_employee.name
     *
     * @param name the value for sys_employee.name
     *
     * @mbg.generated Thu Feb 08 14:08:51 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_employee.mobile
     *
     * @return the value of sys_employee.mobile
     *
     * @mbg.generated Thu Feb 08 14:08:51 CST 2018
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_employee.mobile
     *
     * @param mobile the value for sys_employee.mobile
     *
     * @mbg.generated Thu Feb 08 14:08:51 CST 2018
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_employee.email
     *
     * @return the value of sys_employee.email
     *
     * @mbg.generated Thu Feb 08 14:08:51 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_employee.email
     *
     * @param email the value for sys_employee.email
     *
     * @mbg.generated Thu Feb 08 14:08:51 CST 2018
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_employee.createTime
     *
     * @return the value of sys_employee.createTime
     *
     * @mbg.generated Thu Feb 08 14:08:51 CST 2018
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_employee.createTime
     *
     * @param createtime the value for sys_employee.createTime
     *
     * @mbg.generated Thu Feb 08 14:08:51 CST 2018
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_employee.updateTime
     *
     * @return the value of sys_employee.updateTime
     *
     * @mbg.generated Thu Feb 08 14:08:51 CST 2018
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_employee.updateTime
     *
     * @param updatetime the value for sys_employee.updateTime
     *
     * @mbg.generated Thu Feb 08 14:08:51 CST 2018
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_employee.deleteFlag
     *
     * @return the value of sys_employee.deleteFlag
     *
     * @mbg.generated Thu Feb 08 14:08:51 CST 2018
     */
    public Integer getDeleteflag() {
        return deleteflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_employee.deleteFlag
     *
     * @param deleteflag the value for sys_employee.deleteFlag
     *
     * @mbg.generated Thu Feb 08 14:08:51 CST 2018
     */
    public void setDeleteflag(Integer deleteflag) {
        this.deleteflag = deleteflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_employee.enterpriseId
     *
     * @return the value of sys_employee.enterpriseId
     *
     * @mbg.generated Thu Feb 08 14:08:51 CST 2018
     */
    public Integer getEnterpriseid() {
        return enterpriseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_employee.enterpriseId
     *
     * @param enterpriseid the value for sys_employee.enterpriseId
     *
     * @mbg.generated Thu Feb 08 14:08:51 CST 2018
     */
    public void setEnterpriseid(Integer enterpriseid) {
        this.enterpriseid = enterpriseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_employee.departmentId
     *
     * @return the value of sys_employee.departmentId
     *
     * @mbg.generated Thu Feb 08 14:08:51 CST 2018
     */
    public Integer getDepartmentid() {
        return departmentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_employee.departmentId
     *
     * @param departmentid the value for sys_employee.departmentId
     *
     * @mbg.generated Thu Feb 08 14:08:51 CST 2018
     */
    public void setDepartmentid(Integer departmentid) {
        this.departmentid = departmentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_employee.userId
     *
     * @return the value of sys_employee.userId
     *
     * @mbg.generated Thu Feb 08 14:08:51 CST 2018
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_employee.userId
     *
     * @param userid the value for sys_employee.userId
     *
     * @mbg.generated Thu Feb 08 14:08:51 CST 2018
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_employee.roleId
     *
     * @return the value of sys_employee.roleId
     *
     * @mbg.generated Thu Feb 08 14:08:51 CST 2018
     */
    public Integer getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_employee.roleId
     *
     * @param roleid the value for sys_employee.roleId
     *
     * @mbg.generated Thu Feb 08 14:08:51 CST 2018
     */
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }
}