package com.anrong.user.po;

public class SysRoleMoudle {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_moudle.id
     *
     * @mbg.generated Thu Feb 08 15:24:08 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_moudle.roleId
     *
     * @mbg.generated Thu Feb 08 15:24:08 CST 2018
     */
    private Integer roleid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_moudle.moudleId
     *
     * @mbg.generated Thu Feb 08 15:24:08 CST 2018
     */
    private Integer moudleid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_moudle.id
     *
     * @return the value of sys_role_moudle.id
     *
     * @mbg.generated Thu Feb 08 15:24:08 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_moudle.id
     *
     * @param id the value for sys_role_moudle.id
     *
     * @mbg.generated Thu Feb 08 15:24:08 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_moudle.roleId
     *
     * @return the value of sys_role_moudle.roleId
     *
     * @mbg.generated Thu Feb 08 15:24:08 CST 2018
     */
    public Integer getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_moudle.roleId
     *
     * @param roleid the value for sys_role_moudle.roleId
     *
     * @mbg.generated Thu Feb 08 15:24:08 CST 2018
     */
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_moudle.moudleId
     *
     * @return the value of sys_role_moudle.moudleId
     *
     * @mbg.generated Thu Feb 08 15:24:08 CST 2018
     */
    public Integer getMoudleid() {
        return moudleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_moudle.moudleId
     *
     * @param moudleid the value for sys_role_moudle.moudleId
     *
     * @mbg.generated Thu Feb 08 15:24:08 CST 2018
     */
    public void setMoudleid(Integer moudleid) {
        this.moudleid = moudleid;
    }
}