package com.anrong.user.po;

import java.util.Date;

public class SysUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.id
     *
     * @mbg.generated Thu Feb 08 14:09:10 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.loginCode
     *
     * @mbg.generated Thu Feb 08 14:09:10 CST 2018
     */
    private String logincode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.password
     *
     * @mbg.generated Thu Feb 08 14:09:10 CST 2018
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.createTime
     *
     * @mbg.generated Thu Feb 08 14:09:10 CST 2018
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.updateTime
     *
     * @mbg.generated Thu Feb 08 14:09:10 CST 2018
     */
    private Date updatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.deleteFlag
     *
     * @mbg.generated Thu Feb 08 14:09:10 CST 2018
     */
    private Integer deleteflag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.mobile
     *
     * @mbg.generated Thu Feb 08 14:09:10 CST 2018
     */
    private String mobile;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.id
     *
     * @return the value of sys_user.id
     *
     * @mbg.generated Thu Feb 08 14:09:10 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.id
     *
     * @param id the value for sys_user.id
     *
     * @mbg.generated Thu Feb 08 14:09:10 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.loginCode
     *
     * @return the value of sys_user.loginCode
     *
     * @mbg.generated Thu Feb 08 14:09:10 CST 2018
     */
    public String getLogincode() {
        return logincode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.loginCode
     *
     * @param logincode the value for sys_user.loginCode
     *
     * @mbg.generated Thu Feb 08 14:09:10 CST 2018
     */
    public void setLogincode(String logincode) {
        this.logincode = logincode == null ? null : logincode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.password
     *
     * @return the value of sys_user.password
     *
     * @mbg.generated Thu Feb 08 14:09:10 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.password
     *
     * @param password the value for sys_user.password
     *
     * @mbg.generated Thu Feb 08 14:09:10 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.createTime
     *
     * @return the value of sys_user.createTime
     *
     * @mbg.generated Thu Feb 08 14:09:10 CST 2018
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.createTime
     *
     * @param createtime the value for sys_user.createTime
     *
     * @mbg.generated Thu Feb 08 14:09:10 CST 2018
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.updateTime
     *
     * @return the value of sys_user.updateTime
     *
     * @mbg.generated Thu Feb 08 14:09:10 CST 2018
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.updateTime
     *
     * @param updatetime the value for sys_user.updateTime
     *
     * @mbg.generated Thu Feb 08 14:09:10 CST 2018
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.deleteFlag
     *
     * @return the value of sys_user.deleteFlag
     *
     * @mbg.generated Thu Feb 08 14:09:10 CST 2018
     */
    public Integer getDeleteflag() {
        return deleteflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.deleteFlag
     *
     * @param deleteflag the value for sys_user.deleteFlag
     *
     * @mbg.generated Thu Feb 08 14:09:10 CST 2018
     */
    public void setDeleteflag(Integer deleteflag) {
        this.deleteflag = deleteflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.mobile
     *
     * @return the value of sys_user.mobile
     *
     * @mbg.generated Thu Feb 08 14:09:10 CST 2018
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.mobile
     *
     * @param mobile the value for sys_user.mobile
     *
     * @mbg.generated Thu Feb 08 14:09:10 CST 2018
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }
}