package com.anrong.user.mappers;

import com.anrong.user.po.SysEmployee;
import com.anrong.user.po.SysEmployeeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysEmployeeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_employee
     *
     * @mbg.generated Thu Feb 08 14:08:51 CST 2018
     */
    long countByExample(SysEmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_employee
     *
     * @mbg.generated Thu Feb 08 14:08:51 CST 2018
     */
    int deleteByExample(SysEmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_employee
     *
     * @mbg.generated Thu Feb 08 14:08:51 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_employee
     *
     * @mbg.generated Thu Feb 08 14:08:51 CST 2018
     */
    int insert(SysEmployee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_employee
     *
     * @mbg.generated Thu Feb 08 14:08:51 CST 2018
     */
    int insertSelective(SysEmployee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_employee
     *
     * @mbg.generated Thu Feb 08 14:08:51 CST 2018
     */
    List<SysEmployee> selectByExample(SysEmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_employee
     *
     * @mbg.generated Thu Feb 08 14:08:51 CST 2018
     */
    SysEmployee selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_employee
     *
     * @mbg.generated Thu Feb 08 14:08:51 CST 2018
     */
    int updateByExampleSelective(@Param("record") SysEmployee record, @Param("example") SysEmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_employee
     *
     * @mbg.generated Thu Feb 08 14:08:51 CST 2018
     */
    int updateByExample(@Param("record") SysEmployee record, @Param("example") SysEmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_employee
     *
     * @mbg.generated Thu Feb 08 14:08:51 CST 2018
     */
    int updateByPrimaryKeySelective(SysEmployee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_employee
     *
     * @mbg.generated Thu Feb 08 14:08:51 CST 2018
     */
    int updateByPrimaryKey(SysEmployee record);
}